# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276843605b6e178204ec5e685065328a4fa0756d3712189700e23384503e815910064243c2c14ca3c30536089487b8a42db3aff648eea8dfdabef3ea3b19c2b0

test:
  secret_key_base: b74f94929534fccaf02fc0f40bcff357e311b74906033ffe014fb9e94e243c545adac0ce498ec7697624dd23bd5c782ac2e656cec6ff2bc95d0e796bcd8e9310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
